name: curry_king_pos
description: Curry King Touch Screen Point of Sale System - Professional restaurant ordering and sales management

# Prevent publishing to pub.dev
publish_to: 'none'

# App version - increment for updates
version: 1.0.0+1

# Flutter SDK version constraints
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.0.5

  # Local Data Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Date/Time Formatting
  intl: ^0.18.1

  # Windows Desktop Support
  window_manager: ^0.3.7
  screen_retriever: ^0.1.9
  desktop_window: ^0.4.0

  # Printing System (Windows Compatible)
  printing: ^5.12.0
  pdf: ^3.10.7
  
  # Optional: Bluetooth printing (mobile/some POS systems)
  bluetooth_print: ^4.2.1

  # File and system operations
  path_provider: ^2.1.1
  
  # Optional: Audio feedback for touch
  audioplayers: ^5.2.1
  
  # Optional: HTTP requests (for cloud features, updates)
  http: ^1.1.0

  # Optional: Vibration/haptic feedback (if hardware supports)
  vibration: ^1.8.4

  # Optional: Device information
  device_info_plus: ^9.1.0
  flutter_dotenv: ^5.2.1
  nsd: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter linting rules
  flutter_lints: ^2.0.0

  # Windows installer creation
  msix: ^3.16.7

# Flutter configuration (SINGLE flutter: section)
flutter:
  uses-material-design: true

  # Add the assets section and your .env file here
  assets:
    - .env

# Windows MSIX packaging configuration
msix_config:
  # App identity
  display_name: Curry King Touch POS
  publisher_display_name: Curry King Restaurant
  identity_name: CurryKing.TouchPOS
  msix_version: 1.0.0.0
  
  # App description
  description: Professional Touch Screen Point of Sale System for Curry King Indian Restaurant. Optimized for Windows touch displays.
  
  # Required capabilities for touch POS functionality
  capabilities: 'internetClient,runFullTrust,documentsLibrary,removableStorage'
  
  # Certificate configuration (for production)
  install_certificate: false
  certificate_path: null
  certificate_password: null
  
  # App icons
  logo_path: assets/icons/app_icon.png
  start_menu_icon_path: assets/icons/app_icon.png
  tile_icon_path: assets/icons/app_icon.png
  
  # Architecture (x64 for modern touch POS systems)
  architecture: x64
  
  # Microsoft Store configuration
  store: false
  
  # File associations
  protocol_activation: curry-king-touch-pos
  
  # Execution alias for command line
  execution_alias: curry-king-touch-pos
  
  # Digital signing (set to true for production)
  sign_msix: false
  
  # Supported languages
  languages: en-us
  
  # Installation scope
  install_scope: machine